# render.yaml
services:
  - type: web
    name: sar-atr
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools==65.5.0
      pip install -r requirements.txt
    startCommand: gunicorn app1:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /health